const IMAGES = {
    notFound : new URL('./svg/404.svg', import.meta.url).href,
    coloredLogo : new URL('./svg/colored-logo.svg', import.meta.url).href,
    playStore : new URL('./svg/play-store.svg', import.meta.url).href,
    appStore : new URL('./svg/app-store.svg', import.meta.url).href,
    GoldStar : new URL('./svg/gold-star.svg', import.meta.url).href,
    passager : new URL('./svg/passagers.svg', import.meta.url).href,
    itemTypeImg : new URL('./svg/item-type.svg', import.meta.url).href,
    horse4 : new URL('./svg/horse4.svg', import.meta.url).href,
    fuelTypeImg : new URL('./svg/fuel-type.svg', import.meta.url).href,
    calendar : new URL('./svg/calendar.svg', import.meta.url).href,
    arrowRight : new URL('./svg/arrow-right.svg', import.meta.url).href,
    locationBold : new URL('./svg/location-bold.svg', import.meta.url).href,
    calendarBold : new URL('./svg/calendar-bold.svg', import.meta.url).href,
    carBrand1 : new URL('./svg/partners/honda.svg', import.meta.url).href,
    carBrand2 : new URL('./svg/partners/acura.svg', import.meta.url).href,
    carBrand3 : new URL('./svg/partners/lexus.svg', import.meta.url).href,
    carBrand4 : new URL('./svg/partners/jaguar.svg', import.meta.url).href,
    carBrand5 : new URL('./svg/partners/subaru.svg', import.meta.url).href,
    carBrand6 : new URL('./svg/partners/toyota.svg', import.meta.url).href,
    carBrand7 : new URL('./svg/partners/suzuki.svg', import.meta.url).href,
    carBold : new URL('./svg/car-bold.svg', import.meta.url).href,
    wallet : new URL('./svg/wallet.svg', import.meta.url).href,
    userTick : new URL('./svg/user-tick.svg', import.meta.url).href,
    Support24 : new URL('./svg/24-support.svg', import.meta.url).href,
    messages2 : new URL('./svg/messages-2.svg', import.meta.url).href,
    iPhoneMockup : new URL('./svg/iPhone-mockup.svg', import.meta.url).href,
    footerCall : new URL('./svg/footer/call.svg', import.meta.url).href,
    footerFacebook : new URL('./svg/footer/facebook.svg', import.meta.url).href,
    footerInstagram : new URL('./svg/footer/instagram.svg', import.meta.url).href,
    footerocation : new URL('./svg/footer/location.svg', import.meta.url).href,
    footerSms : new URL('./svg/footer/sms.svg', import.meta.url).href,
    footerYoutube : new URL('./svg/footer/youtube.svg', import.meta.url).href,
    CarBanner : new URL('./png/car.png', import.meta.url).href,
    Car1 : new URL('./png/car1.png', import.meta.url).href,
    Car2 : new URL('./png/car2.png', import.meta.url).href,
    Car3 : new URL('./png/car3.png', import.meta.url).href,
    Car4 : new URL('./png/car4.png', import.meta.url).href,
    audiCar : new URL('./png/audi-car.png', import.meta.url).href,
    user1 : new URL('./png/user1.jpg', import.meta.url).href,
    user2 : new URL('./png/user2.jpg', import.meta.url).href,
    user3 : new URL('./png/user3.jpg', import.meta.url).href,
    user4 : new URL('./png/user4.jpg', import.meta.url).href,
}

export default IMAGES